### PR TITLE
Making use of github flavoured markdown.

### PR DESCRIPTION
**Pull request by huba**
This should make the documentation slightly easier to read.

### CODE REVIEW

**Comment by ioquatix** [comment]
I have a problem with GH markdown. It makes it less readable as actual text. It's better when formatted as HTML. I agree, it's an improvement. But, markdown is supposed to be a readable text format.

I proposed to CommonMark to support a better format, but it was rejected/ignored.

I appreciate your effort.

**Comment by ioquatix** [comment]
https://talk.commonmark.org/t/syntax-highlighting-indented-code/1840/5 was the discussion.

**Comment by ioquatix** [comment]
I thought about this issue a bit more, and changed my opinion. So many tools support "```language" code blocks. I still find it less readable... but perhaps it's okay.

**Comment by huba** [comment]
Is it less readable because the text is not indented or is it because of the fencing?

**Comment by ioquatix** [comment]
Both.

**Pull request closed without merging**
